/*
 * Copyright (c) 2026 Stuart Myatt. All rights reserved.
 * Proprietary — source is public for reference only. See LICENSE at the repository root.
 */
package uk.co.tacklebox.app

import android.Manifest
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.activity.compose.setContent
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavHostController
import androidx.navigation.compose.*
import coil.compose.AsyncImage
import uk.co.tacklebox.app.data.*
import uk.co.tacklebox.app.services.*
import uk.co.tacklebox.app.ui.*
import java.time.*
import java.time.format.DateTimeFormatter
import kotlin.math.roundToInt

class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{TackleboxTheme{TackleboxRoot()}}}}
data class Tab(val route:String,val label:String,val icon:androidx.compose.ui.graphics.vector.ImageVector)
val tabs=listOf(Tab("vault","Vault",Icons.Default.Home),Tab("waters","Waters",Icons.Default.Water),Tab("sessions","Sessions",Icons.Default.Schedule),Tab("insights","Insights",Icons.Default.BarChart))

@Composable fun TackleboxRoot(vm:MainViewModel=viewModel()){
    val state by vm.state.collectAsStateWithLifecycle(); val nav=rememberNavController()
    val back by nav.currentBackStackEntryAsState(); val showFab=back?.destination?.route in setOf("vault","waters","sessions","insights")
    if(!state.settings.onboardingComplete){Onboarding(vm)} else Scaffold(containerColor=Background,bottomBar={BottomBar(nav)},floatingActionButton={if(showFab)FloatingActionButton(onClick={nav.navigate("log")},containerColor=Brass,contentColor=Background,shape=CircleShape){Icon(Icons.Default.Add,"Log a catch")}},floatingActionButtonPosition=FabPosition.Center){pad ->
        NavHost(nav,"vault",Modifier.padding(pad)){
            composable("vault"){Vault(state,nav)}; composable("waters"){Waters(state,nav)}; composable("sessions"){Sessions(state,vm)}; composable("insights"){Insights(state,nav)}; composable("log"){LogCatch(state,vm,nav)}
            composable("tackle"){Tacklebox(state,vm)}; composable("solunar"){Solunar()}; composable("tides"){Tides(vm)}; composable("rivers"){Rivers(vm)}; composable("settings"){Settings(state,vm)}; composable("year"){YearOnWater(state)}
            composable("water/{id}"){WaterPassport(state,it.arguments?.getString("id")?.toLongOrNull())}; composable("species/{id}"){SpeciesDetail(state,it.arguments?.getString("id")?.toLongOrNull(),nav)}; composable("catch/{id}"){CatchDetail(state,it.arguments?.getString("id")?.toLongOrNull())}
        }
    }
}
@Composable fun BottomBar(nav:NavHostController){val back by nav.currentBackStackEntryAsState();NavigationBar(containerColor=Surface){tabs.forEachIndexed{i,t->if(i==2)Spacer(Modifier.weight(.65f));NavigationBarItem(selected=back?.destination?.route==t.route,onClick={nav.navigate(t.route){popUpTo("vault");launchSingleTop=true}},icon={Icon(t.icon,null)},label={Text(t.label)},colors=NavigationBarItemDefaults.colors(selectedIconColor=Brass,selectedTextColor=Brass,indicatorColor=Inset))}}}

@Composable fun Onboarding(vm:MainViewModel){var page by remember{mutableIntStateOf(0)};val request=rememberLauncherForActivityResult(ActivityResultContracts.RequestMultiplePermissions()){};Column(Modifier.fillMaxSize().padding(28.dp),verticalArrangement=Arrangement.SpaceBetween){Column{Text("TACKLEBOX",color=Brass,style=MaterialTheme.typography.labelLarge);Spacer(Modifier.height(48.dp));Text(if(page==0)"Your water.\nYour story." else "Private by design.",style=MaterialTheme.typography.displaySmall);Spacer(Modifier.height(18.dp));Text(if(page==0)"A calm, offline home for catches, waters and days on the bank." else "Your precise fishing spots are never stored. Location is used only when you ask for live conditions.",color=Muted,style=MaterialTheme.typography.bodyLarge)};Column{if(page==0)Button(onClick={page=1},modifier=Modifier.fillMaxWidth()){Text("Continue") } else {Button(onClick={request.launch(arrayOf(Manifest.permission.ACCESS_COARSE_LOCATION))},modifier=Modifier.fillMaxWidth()){Text("Allow live conditions")};Spacer(Modifier.height(10.dp));Button(onClick={vm.seed(true)},modifier=Modifier.fillMaxWidth()){Text("Begin with sample waters")};TextButton(onClick={vm.seed(false)},modifier=Modifier.fillMaxWidth()){Text("Start with an empty vault")}};Text("No account · No tracking · Works offline",Modifier.fillMaxWidth().padding(top=14.dp),textAlign=TextAlign.Center,color=Muted)}}}

@Composable fun Screen(title:String,subtitle:String?=null,actions:@Composable RowScope.()->Unit={},content:LazyListScope.()->Unit){LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(start=18.dp,top=18.dp,end=18.dp,bottom=112.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(title,style=MaterialTheme.typography.headlineLarge);subtitle?.let{Text(it,color=Muted)}};actions()}};content()}}
@Composable fun HeritageCard(modifier:Modifier=Modifier,onClick:(()->Unit)?=null,content:@Composable ColumnScope.()->Unit){Card(modifier=modifier.fillMaxWidth(),colors=CardDefaults.cardColors(containerColor=Surface),shape=RoundedCornerShape(20.dp),onClick=onClick?:{}){Column(Modifier.padding(18.dp),content=content)}}
@Composable fun Stat(value:String,label:String,modifier:Modifier=Modifier){Column(modifier.background(Inset,RoundedCornerShape(16.dp)).padding(14.dp)){Text(value,color=BrassSoft,style=MaterialTheme.typography.titleLarge);Text(label,color=Muted,style=MaterialTheme.typography.bodyMedium)}}
fun Double.weight(unit:UnitSystem)=if(unit==UnitSystem.METRIC) if(this>=1000)"%.2f kg".format(this/1000) else "%.0f g".format(this) else {val oz=this/28.3495;"${(oz/16).toInt()} lb ${(oz%16).roundToInt()} oz"}
fun Instant.pretty():String=atZone(ZoneId.systemDefault()).format(DateTimeFormatter.ofPattern("d MMM yyyy · HH:mm"))

@Composable fun Vault(s:AppState,nav:NavHostController){val pb=s.catches.filter{it.item.weightGrams!=null}.maxByOrNull{it.item.weightGrams!!};val sol=Astronomy.calculate();Screen("The Vault","A private ledger of time well spent",actions={IconButton({nav.navigate("settings")}){Icon(Icons.Default.Settings,"Settings")}}){item{HeritageCard(onClick=pb?.let{{nav.navigate("catch/${it.item.id}")}}){Text("FEATURED PERSONAL BEST",color=Brass,style=MaterialTheme.typography.labelLarge);Spacer(Modifier.height(12.dp));Text(pb?.species?.name?:"Your finest catch awaits",style=MaterialTheme.typography.headlineMedium);Text(pb?.item?.weightGrams?.weight(s.settings.unitSystem)?:"Log a catch to begin your board",color=Muted)}};item{HeritageCard(onClick={nav.navigate("solunar")}){Text("TODAY ON THE BANK",color=Teal,style=MaterialTheme.typography.labelLarge);Text("${sol.rating}/5 day · ${sol.moonPhase}",style=MaterialTheme.typography.titleLarge);Text("Next window ${sol.windows.first().start}–${sol.windows.first().end}  ·  ↑ ${sol.sunrise}  ↓ ${sol.sunset}",color=Muted)}};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Stat("${s.catches.size}","fish landed",Modifier.weight(1f));Stat("${s.catches.mapNotNull{it.species?.id}.distinct().size}","species",Modifier.weight(1f));Stat("${s.waters.size}","waters",Modifier.weight(1f))}};item{Text("Personal best board",style=MaterialTheme.typography.titleLarge)};items(s.catches.filter{it.item.weightGrams!=null}.groupBy{it.species?.id}.mapNotNull{(_,v)->v.maxByOrNull{it.item.weightGrams?:0.0}}){c->HeritageCard(onClick={nav.navigate("species/${c.species?.id}")}){Row{Text(c.species?.name?:"Unknown",Modifier.weight(1f));Text(c.item.weightGrams?.weight(s.settings.unitSystem).orEmpty(),color=BrassSoft)}}};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){AssistChip({nav.navigate("tackle")},{Text("My Tacklebox")},leadingIcon={Icon(Icons.Default.Inventory2,null)});AssistChip({nav.navigate("solunar")},{Text("Bite windows")},leadingIcon={Icon(Icons.Default.DarkMode,null)})}}}}

@Composable fun Waters(s:AppState,nav:NavHostController){Screen("Waters","Your places, kept private"){item{HeritageCard(onClick={nav.navigate("rivers")}){Text("River conditions",style=MaterialTheme.typography.titleLarge);Text("Levels, flow and nearby gauges",color=Muted)}};item{HeritageCard(onClick={nav.navigate("tides")}){Text("Tides & sea",style=MaterialTheme.typography.titleLarge);Text("Coastal waves and sea state",color=Muted)}};item{Text("Water passports",style=MaterialTheme.typography.titleLarge)};if(s.waters.isEmpty())item{Empty("No waters saved","Start a session to build your private map.")};items(s.waters){w->HeritageCard(onClick={nav.navigate("water/${w.id}")}){Row{Icon(Icons.Default.Water,null,tint=Teal);Spacer(Modifier.width(12.dp));Column{Text(w.name,style=MaterialTheme.typography.titleLarge);Text("${w.type.name.lowercase().replaceFirstChar(Char::uppercase)} · ${w.region}",color=Muted)}}}}}}
@Composable fun WaterPassport(s:AppState,id:Long?){val w=s.waters.firstOrNull{it.id==id};val catches=s.catches.filter{it.water?.id==id};Screen(w?.name?:"Water passport",w?.region){item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Stat("${catches.size}","catches",Modifier.weight(1f));Stat("${catches.mapNotNull{it.species}.distinctBy{it.id}.size}","species",Modifier.weight(1f))}};item{HeritageCard{Text("Private swim notes",color=Brass);Text(w?.swimNotes?.ifBlank{"No notes yet."}?:"No notes yet.",color=Muted)}};item{Text("Most productive",style=MaterialTheme.typography.titleLarge);Text(catches.groupingBy{it.species?.name?:"Unknown"}.eachCount().maxByOrNull{it.value}?.key?:"Log catches here to reveal patterns",color=Muted)}}}

@Composable fun Sessions(s:AppState,vm:MainViewModel){var selected by remember{mutableStateOf<Long?>(s.waters.firstOrNull()?.id)};val active=s.sessions.firstOrNull{it.item.endAt==null};Screen("Sessions","Hours on the bank, remembered"){item{HeritageCard{if(active==null){Text("Start a session",style=MaterialTheme.typography.titleLarge);s.waters.forEach{FilterChip(selected==it.id,{selected=it.id},{Text(it.name)})};Button({vm.startSession(selected)},enabled=s.waters.isNotEmpty()){Text("Start fishing")}}else{Text("Session in progress",color=Teal);Text(active.water?.name?:"Unspecified water",style=MaterialTheme.typography.headlineMedium);Button({vm.stopSession(active.item.id)}){Text("Finish session")}}}};items(s.sessions){x->HeritageCard{Text(x.water?.name?:"Unspecified water",style=MaterialTheme.typography.titleLarge);Text("${x.item.startAt.pretty()} · ${x.catches.size} catches",color=Muted);Text(if(x.item.endAt==null)"LIVE" else "Finished",color=if(x.item.endAt==null)Teal else Brass)}}}}

@Composable fun Insights(s:AppState,nav:NavHostController){val total=s.catches.mapNotNull{it.item.weightGrams}.sum();Screen("Insights","Patterns emerge from patient notes"){item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Stat("${s.catches.size}","landed",Modifier.weight(1f));Stat(total.weight(s.settings.unitSystem),"total weight",Modifier.weight(1f))}};item{HeritageCard(onClick={nav.navigate("year")}){Text("YEAR ON THE WATER",color=Brass);Text("Your season, distilled",style=MaterialTheme.typography.headlineMedium);Text("Open shareable summary →",color=Muted)}};item{Breakdown("Catches over time",s.catches.groupingBy{it.item.caughtAt.atZone(ZoneId.systemDefault()).month.name.take(3)}.eachCount())};item{Breakdown("Species",s.catches.groupingBy{it.species?.name?:"Unknown"}.eachCount())};item{Breakdown("Waters",s.catches.groupingBy{it.water?.name?:"Unspecified"}.eachCount())};item{HeritageCard{Text("Conditions insight",style=MaterialTheme.typography.titleLarge);Text(if(s.catches.size<3)"Log three or more catches to reveal weather patterns." else "Your catches favour stable pressure around dawn and dusk.",color=Muted)}}}}
@Composable fun Breakdown(title:String,data:Map<String,Int>){HeritageCard{Text(title,style=MaterialTheme.typography.titleLarge);if(data.isEmpty())Text("Not enough data yet",color=Muted) else data.entries.sortedByDescending{it.value}.take(5).forEach{Row(Modifier.padding(top=8.dp)){Text(it.key,Modifier.weight(1f));Text("${it.value}",color=Brass)}}}}
@Composable fun YearOnWater(s:AppState){val year=Year.now().value;val catches=s.catches.filter{it.item.caughtAt.atZone(ZoneId.systemDefault()).year==year};val biggest=catches.maxByOrNull{it.item.weightGrams?:0.0};val hours=s.sessions.filter{it.item.endAt!=null}.sumOf{Duration.between(it.item.startAt,it.item.endAt!!).toMinutes()}/60;Screen("Year on the Water","$year · a season worth keeping"){item{Card(colors=CardDefaults.cardColors(containerColor=Inset),shape=RoundedCornerShape(28.dp)){Column(Modifier.padding(26.dp)){Text("TACKLEBOX · $year",color=Brass);Text("${catches.size}",style=MaterialTheme.typography.displaySmall);Text("fish landed",color=Muted);HorizontalDivider(Modifier.padding(vertical=16.dp));Text("${catches.mapNotNull{it.item.weightGrams}.sum().weight(s.settings.unitSystem)} carried gently");Text("${biggest?.species?.name?:"No biggest fish yet"} · ${biggest?.item?.weightGrams?.weight(s.settings.unitSystem).orEmpty()}");Text("$hours hours on the bank");Text("Top bait · ${catches.groupingBy{it.item.bait?:"Unrecorded"}.eachCount().maxByOrNull{it.value}?.key?:"—"}",color=BrassSoft)}}};item{Button({},Modifier.fillMaxWidth()){Icon(Icons.Default.Share,null);Spacer(Modifier.width(8.dp));Text("Share summary")}}}}

@Composable fun LogCatch(s:AppState,vm:MainViewModel,nav:NavHostController){var species by remember{mutableStateOf<Long?>(s.species.firstOrNull()?.id)};var weight by remember{mutableStateOf("")};var length by remember{mutableStateOf("")};var rig by remember{mutableStateOf("")};var bait by remember{mutableStateOf("")};var returned by remember{mutableStateOf(true)};var photo by remember{mutableStateOf<String?>(null)};val picker=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){photo=it?.toString()};Screen("Log a catch","A quiet record of the moment"){item{HeritageCard{Box(Modifier.fillMaxWidth().height(150.dp).clip(RoundedCornerShape(14.dp)).background(Inset).clickable{picker.launch("image/*")},contentAlignment=Alignment.Center){if(photo==null)Column(horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.AddAPhoto,null,tint=Brass);Text("Add photo",color=Muted)}else AsyncImage(photo,null,Modifier.fillMaxSize(),contentScale=ContentScale.Crop)}}};item{Text("Species",style=MaterialTheme.typography.titleLarge);LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){items(s.species){sp->FilterChip(species==sp.id,{species=sp.id},{Text(sp.name)})}}};item{if(s.settings.speciesIdToken.isBlank())Text("Species ID is available after adding your own token in Settings.",color=Muted) else OutlinedButton({}){Icon(Icons.Default.AutoAwesome,null);Text(" Identify from photo")}};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(weight,{weight=it},label={Text(if(s.settings.unitSystem==UnitSystem.METRIC)"Weight (g)" else "Weight (oz)")},modifier=Modifier.weight(1f));OutlinedTextField(length,{length=it},label={Text("Length (cm)")},modifier=Modifier.weight(1f))}};item{OutlinedTextField(rig,{rig=it},label={Text("Rig")},modifier=Modifier.fillMaxWidth());OutlinedTextField(bait,{bait=it},label={Text("Bait")},modifier=Modifier.fillMaxWidth())};item{Row(verticalAlignment=Alignment.CenterVertically){Text("Returned",Modifier.weight(1f));Switch(returned,{returned=it})}};item{Button(onClick={val grams=weight.toDoubleOrNull()?.let{if(s.settings.unitSystem==UnitSystem.IMPERIAL)it*28.3495 else it};vm.addCatch(species,grams,length.toDoubleOrNull(),rig,bait,returned,null,photo){nav.navigate("catch/$it"){popUpTo("vault")}}},modifier=Modifier.fillMaxWidth(),enabled=species!=null){Text("Save catch")}}}}

@Composable fun Tacklebox(s:AppState,vm:MainViewModel){var name by remember{mutableStateOf("")};Screen("My Tacklebox","Gear that earns its place"){item{HeritageCard{Text("Gear performance",color=Brass);Text("Best rig · ${s.catches.groupingBy{it.item.rig?:"Unrecorded"}.eachCount().maxByOrNull{it.value}?.key?:"—"}");Text("Top bait · ${s.catches.groupingBy{it.item.bait?:"Unrecorded"}.eachCount().maxByOrNull{it.value}?.key?:"—"}",color=Muted)}};items(s.gear){g->HeritageCard{Text(g.name,style=MaterialTheme.typography.titleLarge);Text(g.category.name.lowercase().replaceFirstChar(Char::uppercase),color=Muted)}};item{OutlinedTextField(name,{name=it},label={Text("New gear or preset")},modifier=Modifier.fillMaxWidth());Row{Button({if(name.isNotBlank()){vm.addGear(name,GearCategory.OTHER);name=""}}){Text("Add gear")};Spacer(Modifier.width(8.dp));OutlinedButton({if(name.isNotBlank()){vm.addPreset(name,PresetKind.RIG);name=""}}){Text("Save rig")}}};item{Text("Quick picks",style=MaterialTheme.typography.titleLarge);Text(s.presets.joinToString(" · "){it.name}.ifBlank{"No saved rigs or baits"},color=Muted)}}}

@Composable fun Solunar(){val d=Astronomy.calculate();Screen("Bite windows","Calculated on-device for today"){item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Stat("${d.rating}/5","day rating",Modifier.weight(1f));Stat(d.moonPhase,"moon",Modifier.weight(1f))}};item{HeritageCard{Text("Sun & moon",style=MaterialTheme.typography.titleLarge);Text("Sunrise ${d.sunrise}  ·  Sunset ${d.sunset}",color=Muted);Text("Moonrise ${d.moonrise}",color=Muted)}};items(d.windows){w->HeritageCard{Row{Column(Modifier.weight(1f)){Text(w.label);Text(if(w.major)"Major feeding period" else "Minor feeding period",color=if(w.major)Brass else Muted)};Text("${w.start}–${w.end}")}}}}}
@Composable fun Tides(vm:MainViewModel){val live by vm.marine.collectAsStateWithLifecycle();LaunchedEffect(Unit){vm.marine()};Screen("Tides & sea","Live coastal outlook · Open-Meteo"){item{when(val x=live){LiveState.Idle,LiveState.Loading->Loading();is LiveState.Error->ErrorCard(x.message){vm.marine()};is LiveState.Data->{val h=x.value.hourly;if(h==null||h.waveHeight.isEmpty())Empty("No coastal data","You may be inland or outside forecast coverage.") else HeritageCard{Text("Sea state",style=MaterialTheme.typography.headlineMedium);h.time.take(8).forEachIndexed{i,t->Row{Text(t.takeLast(5),Modifier.weight(1f));Text("${h.waveHeight.getOrNull(i)?:0.0} m · ${h.wavePeriod.getOrNull(i)?:0.0} s",color=Teal)}}}}}}}}
@Composable fun Rivers(vm:MainViewModel){val live by vm.river.collectAsStateWithLifecycle();LaunchedEffect(Unit){vm.river()};Screen("River conditions","Environment Agency gauges"){item{when(val x=live){LiveState.Idle,LiveState.Loading->Loading();is LiveState.Error->ErrorCard(x.message){vm.river()};is LiveState.Data->if(x.value.items.isEmpty())Empty("No nearby gauges","Try again nearer a gauged river.")else Column{Text("Nearby readings",style=MaterialTheme.typography.titleLarge);x.value.items.take(8).forEach{HeritageCard{Text(it.value?.let{"$it m"}?:"Reading unavailable");Text(it.dateTime?:"Latest observation",color=Muted)}}}}}}}

@Composable fun SpeciesDetail(s:AppState,id:Long?,nav:NavHostController){val sp=s.species.firstOrNull{it.id==id};val catches=s.catches.filter{it.species?.id==id};Screen(sp?.name?:"Species record",sp?.scientificName){item{Box(Modifier.fillMaxWidth().height(170.dp).background(Inset,RoundedCornerShape(22.dp)),contentAlignment=Alignment.Center){Icon(Icons.Default.SetMeal,null,tint=Brass,modifier=Modifier.size(64.dp))}};item{Text(sp?.about?:"A personal record built from your catches.",color=Muted)};item{Text("Catch history",style=MaterialTheme.typography.titleLarge)};items(catches){c->HeritageCard(onClick={nav.navigate("catch/${c.item.id}")}){Text(c.item.caughtAt.pretty());Text(c.item.weightGrams?.weight(s.settings.unitSystem)?:"Weight not recorded",color=Brass)}}}}
@Composable fun CatchDetail(s:AppState,id:Long?){val c=s.catches.firstOrNull{it.item.id==id};Screen(c?.species?.name?:"Catch detail",c?.item?.caughtAt?.pretty()){item{Box(Modifier.fillMaxWidth().height(220.dp).clip(RoundedCornerShape(22.dp)).background(Inset),contentAlignment=Alignment.Center){if(c?.item?.photoUri!=null)AsyncImage(c.item.photoUri,null,Modifier.fillMaxSize(),contentScale=ContentScale.Crop)else Icon(Icons.Default.SetMeal,null,tint=Brass,modifier=Modifier.size(72.dp))}};item{HeritageCard{Text(c?.item?.weightGrams?.weight(s.settings.unitSystem)?:"Weight not recorded",style=MaterialTheme.typography.headlineMedium);Text("${c?.water?.name?:"Water not recorded"} · ${if(c?.item?.returned==true)"Returned" else "Kept"}",color=Muted)}};item{HeritageCard{Text("Tackle",color=Brass);Text("Rig · ${c?.item?.rig?.ifBlank{"Not recorded"}?:"Not recorded"}");Text("Bait · ${c?.item?.bait?.ifBlank{"Not recorded"}?:"Not recorded"}")}};item{HeritageCard{Text("Conditions",color=Teal);Text("Moon · ${c?.conditions?.moonPhase?:"Not available"}");Text("Weather snapshot unavailable offline",color=Muted)}}}}

@Composable fun Settings(s:AppState,vm:MainViewModel){
    var token by remember(s.settings.speciesIdToken){mutableStateOf(s.settings.speciesIdToken)}
    var confirm by remember{mutableStateOf(false)}
    Screen("Settings","Your data, your choices"){
        item{HeritageCard{Text("Units",style=MaterialTheme.typography.titleLarge);SingleChoiceSegmentedButtonRow{UnitSystem.entries.forEachIndexed{i,u->SegmentedButton(s.settings.unitSystem==u,{vm.settings(s.settings.copy(unitSystem=u))},SegmentedButtonDefaults.itemShape(i,2)){Text(u.name.lowercase().replaceFirstChar(Char::uppercase))}}}}}
        item{HeritageCard{Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Google Drive backup");Text("Off by default · app-data scope",color=Muted)};Switch(s.settings.backupEnabled,{vm.settings(s.settings.copy(backupEnabled=it))})};if(s.settings.backupEnabled)Text("Drive backup requires an OAuth client configured for this app build; local data remains authoritative.",color=Muted,style=MaterialTheme.typography.bodyMedium)}}
        item{OutlinedTextField(token,{token=it},label={Text("Species-ID API token")},visualTransformation=androidx.compose.ui.text.input.PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth());Button({vm.settings(s.settings.copy(speciesIdToken=token))}){Text("Save token")}}
        item{HeritageCard{Text("Data",style=MaterialTheme.typography.titleLarge);OutlinedButton({},Modifier.fillMaxWidth()){Icon(Icons.Default.FileDownload,null);Text(" Export JSON")};TextButton({confirm=true},Modifier.fillMaxWidth(),colors=ButtonDefaults.textButtonColors(contentColor=MaterialTheme.colorScheme.error)){Text("Delete catches, waters & gear")}}}
        item{Text("No ads · No analytics · No subscriptions",Modifier.fillMaxWidth(),textAlign=TextAlign.Center,color=Muted)}
    }
    if(confirm)AlertDialog(onDismissRequest={confirm=false},title={Text("Delete your data?")},text={Text("This removes catches, sessions, waters, gear and presets from this device. Species and settings remain.")},confirmButton={TextButton({vm.deleteData();confirm=false}){Text("Delete")}},dismissButton={TextButton({confirm=false}){Text("Cancel")}})
}
@Composable fun Empty(title:String,body:String){Column(Modifier.fillMaxWidth().padding(30.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.SetMeal,null,tint=Brass);Text(title,style=MaterialTheme.typography.titleLarge);Text(body,color=Muted,textAlign=TextAlign.Center)}}
@Composable fun Loading(){Box(Modifier.fillMaxWidth().padding(40.dp),contentAlignment=Alignment.Center){CircularProgressIndicator(color=Brass)}}
@Composable fun ErrorCard(message:String,retry:()->Unit){HeritageCard{Text(message,color=MaterialTheme.colorScheme.error);TextButton(retry){Text("Try again")}}}